services:
  api:
    image: anthonyvillazana/votabien_backend:latest
    container_name: politics_api
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    command: sh /app/entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://votabienperu.com/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: politics_network