"""fix json field

Revision ID: 620ff9f7e644
Revises: f8e24e4d27da
Create Date: 2025-10-17 12:52:19.337652

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "620ff9f7e644"
down_revision: Union[str, Sequence[str], None] = "f8e24e4d27da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "partidopolitico",
        "historia_timeline",
        type_=sa.JSON(),
        existing_nullable=True,
        postgresql_using="historia_timeline::json",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "partidopolitico",
        "historia_timeline",
        type_=sa.TEXT(),
        existing_nullable=True,
        postgresql_using="historia_timeline::text",
    )
    # ### end Alembic commands ###
