"""experiencia_laboral

Revision ID: 733f915d9aec
Revises: ecce50cee972
Create Date: 2025-10-18 12:44:02.399257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733f915d9aec'
down_revision: Union[str, Sequence[str], None] = 'ecce50cee972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('experiencia_laboral', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'experiencia_laboral')
    # ### end Alembic commands ###
