"""add ant edu fields

Revision ID: a1a6f61191b9
Revises: 649b87cb5091
Create Date: 2025-10-16 23:27:56.281190

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1a6f61191b9"
down_revision: Union[str, Sequence[str], None] = "649b87cb5091"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona",
        sa.Column(
            "educacion_tecnica",
            sqlmodel.sql.sqltypes.AutoString(length=300),
            nullable=True,
        ),
    )
    op.add_column(
        "persona",
        sa.Column(
            "educacion_universitaria",
            sqlmodel.sql.sqltypes.AutoString(length=300),
            nullable=True,
        ),
    )
    op.add_column(
        "persona",
        sa.Column(
            "grado_academico",
            sqlmodel.sql.sqltypes.AutoString(length=300),
            nullable=True,
        ),
    )
    op.add_column(
        "persona",
        sa.Column(
            "titulo_profesional",
            sqlmodel.sql.sqltypes.AutoString(length=300),
            nullable=True,
        ),
    )
    op.add_column(
        "persona",
        sa.Column(
            "post_grado", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True
        ),
    )
    op.add_column(
        "persona", sa.Column("antecedentes_penales", sa.JSON(), nullable=True)
    )
    op.add_column(
        "persona", sa.Column("antecedentes_judiciales", sa.JSON(), nullable=True)
    )
    op.drop_column("persona", "resumen_antecedentes")
    op.drop_column("persona", "tiene_antecedentes_penales")
    op.drop_column("persona", "educacion_superior")
    op.drop_column("persona", "tiene_antecedentes_judiciales")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona",
        sa.Column(
            "tiene_antecedentes_judiciales",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "persona",
        sa.Column(
            "educacion_superior",
            sa.VARCHAR(length=300),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "persona",
        sa.Column(
            "tiene_antecedentes_penales",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "persona",
        sa.Column(
            "resumen_antecedentes", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("persona", "antecedentes_judiciales")
    op.drop_column("persona", "antecedentes_penales")
    op.drop_column("persona", "post_grado")
    op.drop_column("persona", "titulo_profesional")
    op.drop_column("persona", "grado_academico")
    op.drop_column("persona", "educacion_universitaria")
    op.drop_column("persona", "educacion_tecnica")
    # ### end Alembic commands ###
