"""move hoja_vida_url

Revision ID: ecce50cee972
Revises: 620ff9f7e644
Create Date: 2025-10-18 11:55:11.992738

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecce50cee972"
down_revision: Union[str, Sequence[str], None] = "620ff9f7e644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidato", "hoja_vida_url")
    op.add_column(
        "persona",
        sa.Column("hoja_vida_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persona", "hoja_vida_url")
    op.add_column(
        "candidato",
        sa.Column("hoja_vida_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
