"""add partidopoli fields

Revision ID: f8e24e4d27da
Revises: a1a6f61191b9
Create Date: 2025-10-17 12:25:58.566634

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8e24e4d27da"
down_revision: Union[str, Sequence[str], None] = "a1a6f61191b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "partidopolitico",
        sa.Column(
            "fundador", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
    )
    op.add_column(
        "partidopolitico", sa.Column("fecha_fundacion", sa.Date(), nullable=True)
    )
    op.add_column(
        "partidopolitico",
        sa.Column(
            "descripcion", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
    )
    op.add_column(
        "partidopolitico",
        sa.Column(
            "ideologia", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
    )
    op.add_column(
        "partidopolitico",
        sa.Column(
            "sede_nacional", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True
        ),
    )
    op.add_column(
        "partidopolitico",
        sa.Column(
            "telefono", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
    )
    op.add_column(
        "partidopolitico",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    )
    op.add_column(
        "partidopolitico",
        sa.Column(
            "sitio_web", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
    )
    op.add_column(
        "partidopolitico", sa.Column("financiamiento_anual", sa.Float(), nullable=True)
    )
    op.add_column(
        "partidopolitico", sa.Column("gasto_campana_ultima", sa.Float(), nullable=True)
    )
    op.add_column(
        "partidopolitico",
        sa.Column(
            "fuente_financiamiento",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
    )
    op.add_column(
        "partidopolitico", sa.Column("historia_timeline", sa.Text(), nullable=True)
    )
    op.add_column(
        "partidopolitico",
        sa.Column("facebook_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "partidopolitico",
        sa.Column("twitter_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "partidopolitico",
        sa.Column("instagram_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "partidopolitico",
        sa.Column("youtube_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "partidopolitico", sa.Column("total_militantes", sa.Integer(), nullable=True)
    )
    op.add_column(
        "partidopolitico", sa.Column("total_escaños", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("partidopolitico", "total_escaños")
    op.drop_column("partidopolitico", "total_militantes")
    op.drop_column("partidopolitico", "youtube_url")
    op.drop_column("partidopolitico", "instagram_url")
    op.drop_column("partidopolitico", "twitter_url")
    op.drop_column("partidopolitico", "facebook_url")
    op.drop_column("partidopolitico", "historia_timeline")
    op.drop_column("partidopolitico", "fuente_financiamiento")
    op.drop_column("partidopolitico", "gasto_campana_ultima")
    op.drop_column("partidopolitico", "financiamiento_anual")
    op.drop_column("partidopolitico", "sitio_web")
    op.drop_column("partidopolitico", "email")
    op.drop_column("partidopolitico", "telefono")
    op.drop_column("partidopolitico", "sede_nacional")
    op.drop_column("partidopolitico", "ideologia")
    op.drop_column("partidopolitico", "descripcion")
    op.drop_column("partidopolitico", "fecha_fundacion")
    op.drop_column("partidopolitico", "fundador")
    # ### end Alembic commands ###
