name: Deploy Backend to Dokploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Construir y publicar la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/votabien_backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/votabien_backend:${{ github.sha }}

      # 4️⃣ Desplegar en Dokploy automáticamente
      - name: Trigger Dokploy Deployment
        if: success() && ${{ secrets.DOKPLOY_DEPLOY_HOOK }} != ''
        run: |
          echo "🚀 Triggering Dokploy deploy..."
          curl -X POST "${{ secrets.DOKPLOY_DEPLOY_HOOK }}"
